library(Seurat)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(ggridges)
setwd()
matrix<-read.delim('GSE120084_Raw_read_counts_PhenoMap.txt.gz')
row.names(matrix)<-make.names(matrix$GeneID,unique = TRUE)
matrix<-matrix[,-1]
data<-CreateSeuratObject(counts = matrix)
head(data@active.ident)
gc()
data[["percent.mt"]] <- PercentageFeatureSet(data, pattern = "^MT-")
VlnPlot(data, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol=3)
FeatureScatter(data, feature1 = "nCount_RNA", feature2 = "nFeature_RNA") + geom_smooth()
data <- NormalizeData(data)
data <- FindVariableFeatures(data, selection.method = "vst", nfeatures = 2000)
VariableFeatures(data)
top10 <- head(VariableFeatures(data), 10)
top10
gc()
plot1 <- VariableFeaturePlot(data)
plot1
all.genes <- rownames(data)
all.genes
gc()
data <- ScaleData(data, features = all.genes)
gc()
dim(data)
data <- RunPCA(data,npcs = 18, features = VariableFeatures(object = data))
DimHeatmap(data, dims = 1:15, cells = 500, balanced = T)
ElbowPlot(data)
gc()
#Figure 2b
VlnPlot(data,features = c('MRC1','DDX58','IFIH1','DHX58','NFKB1','CD274','PDCD1LG2','IL6ST','MILR1'),idents = c('IFNY.LPS','IL4'),cols = c('red','skyblue'))
FindMarkers(data, ident.1 = 'IFNY.LPS', ident.2 = 'IL4', features = c('MRC1','DDX58','IFIH1','DHX58','NFKB1','CD274','PDCD1LG2','IL6ST','MILR1'))
