library(Seurat)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(ggridges)
setwd()
matrix<-read.csv('GSE132761_RNAseq_rawcounts.csv')
row.names(matrix)<-make.names(matrix$Gene,unique = TRUE)
matrix<-matrix[,-1]
data<-CreateSeuratObject(counts = matrix)
head(data@active.ident)
gc()
data[["percent.mt"]] <- PercentageFeatureSet(data, pattern = "^MT-")
VlnPlot(data, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol=3)
FeatureScatter(data, feature1 = "nCount_RNA", feature2 = "nFeature_RNA") + geom_smooth()
data <- NormalizeData(data)
data <- FindVariableFeatures(data, selection.method = "vst", nfeatures = 2000)
VariableFeatures(data)
top10 <- head(VariableFeatures(data), 10)
top10
gc()
plot1 <- VariableFeaturePlot(data)
plot1
all.genes <- rownames(data)
all.genes
gc()
data <- ScaleData(data, features = all.genes)
gc()
dim(data)
data <- RunPCA(data,npcs = 8, features = VariableFeatures(object = data))
DimHeatmap(data, dims = 1:8, cells = 500, balanced = T)
ElbowPlot(data)
gc()
VlnPlot(data,features = c('GATA3','TBX21','CD4','PDCD1','DDX58','IFIH1'),idents = c('IL6.3hr','IL6.48hr'),cols = c('grey','green'))
FindMarkers(data, ident.1 = 'IL6.48hr', ident.2 = 'IL6.3hr', features = c('GATA3','TBX21','CD4','PDCD1','DDX58','IFIH1'))
break
